@echo off

set AWS_DEFAULT_REGION=us-east-1
set AWS_ACCESS_KEY_ID=ASIA5DREFSPA35ACAA5O
set AWS_SECRET_ACCESS_KEY=U4LlAy5nzOjsd3D5bKblyTQOilAwSu4okvpFH4rP
set AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEI///////////wEaCXVzLWVhc3QtMSJHMEUCIQDWUpVwhAP7JNIhbHVBnd1J2M2T0rBdgBSaUqPepVm/sAIgcnnq3FABJ4Zlp5MU+yNQ5KQ7gp5L8HLlWabv6NbggTwqoAIImP//////////ARABGgw5MDA5NDUyNTMzMTMiDJqF2bAwhR1OqoSDzyr0AWknv3gAaRaGZsRVjKM4qa/osvZnKTmCYQkjqK3/IlB9BaB2LXvTCmvPZdqUzCSXiNsqErqMDjhcoFf9HloxSTK7WSFFBA0Usvik5Znr/K4oBvmfntu4B1l917AwqM809FKt5t2CUJbPh4PH8O0l0Man/KMbQYGNtDFHo42stWWeRYfg1HTl6zFDImAl12zdhqI1qvYcB8mGUh1hzob6aN8uDLQ0AomXnjLeupeMcSSrT9kkMX2rzqBnRnYGJJrFVbwbfTtCgvGRvWlD0+45uaam/8YFFKpZhpJZwFJkhwWQBdTv1N0YFYNzMupbbBSyZ6Dg/hIwk7mHqQY6nQEyXYgcn3lMV2qbx6Ph498I8Sy1xXmbUun7wxOgk0aYtyT1lKR54Y2Y+T5DkCmcIHSx7jbxs05Kb3PtKhTDVyHDqcJkypSOLYkTNmUhVmUBDD6CxZtQhIzCPPYa45094mYxyLYv3Y7hngGlNqVyOMQhe4F178tiza/I85lZcw3SSkV2DHsG/NP0TLMrfxYlN1dPrfYpZfBeIiIJ1iSZ

rem Navigate to the Spring Boot project directory
cd "backend"

rem Start the Spring Boot application using Gradle
start /min cmd /k "gradlew.bat bootRun"

rem Open a new command prompt window and navigate to the Angular project directory
cd "..\ui\frontend"
start /min cmd /k "ng serve"

